name: Continuous Integration

on:
  pull_request:
    branches:
      - develop
      - alpha
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Lint check
        run: npx eslint *.js

      - name: Run tests
        run: npx jest
